# ################################################################################
#  Copyright (c) 2025  Claudio André <portfolio-2025br at claudioandre.slmail.me>
#      ____              __                                _       _________  __
#     / __ )____  ____  / /__________ _____ ___  ____     | |     / / ____/ |/ /
#    / __  / __ \/ __ \/ __/ ___/ __ `/ __ `__ \/ __ \    | | /| / / __/  |   /
#   / /_/ / /_/ / /_/ / /_/ /__/ /_/ / / / / / / /_/ /    | |/ |/ / /___ /   |
#  /_____/\____/\____/\__/\___/\__,_/_/ /_/ /_/ .___/     |__/|__/_____//_/|_|
#                                            /_/
#
# This program comes with ABSOLUTELY NO WARRANTY; express or implied.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, as expressed in version 2, seen at
# https://www.gnu.org/licenses/gpl-2.0.html
###############################################################################
# GitHub Action to approve PRs
# More info at https://github.com/portfolio-2025br/bootcamp-csharp

---
name: Approve it

"on":
  workflow_dispatch:
    #checkov:skip=CKV_GHA_7:This is automation, not a real build
    inputs:
      pullRequestNumber:
        description: Pull request number
        required: true

permissions:
  contents: read

jobs:
  approve-pr:
    runs-on: ubuntu-latest
    name: approve-pr

    permissions:
      pull-requests: write

    if: github.actor == 'portfolio-2025br'
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@ec9f2d5744a09debf3a187a3f4f675c53b671911 # v2.13.0
        with:
          disable-sudo-and-containers: true
          egress-policy: block
          allowed-endpoints: >
            api.github.com:443

      - uses: hmarr/auto-approve-action@f0939ea97e9205ef24d872e76833fa908a770363 # v4.0.0
        with:
          pull-request-number: ${{ github.event.inputs.pullRequestNumber }}
          review-message: "Auto approved PR"
