# ##############################################################################
#       Copyright (c) 2025   Claudio André <dev at claudioandre.slmail.me>
#      ____              __                                _       _________  __
#     / __ )____  ____  / /__________ _____ ___  ____     | |     / / ____/ |/ /
#    / __  / __ \/ __ \/ __/ ___/ __ `/ __ `__ \/ __ \    | | /| / / __/  |   /
#   / /_/ / /_/ / /_/ / /_/ /__/ /_/ / / / / / / /_/ /    | |/ |/ / /___ /   |
#  /_____/\____/\____/\__/\___/\__,_/_/ /_/ /_/ .___/     |__/|__/_____//_/|_|
#                                            /_/
#
# This program comes with ABSOLUTELY NO WARRANTY; express or implied.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, as expressed in version 2, seen at
# https://www.gnu.org/licenses/gpl-2.0.html
# ##############################################################################
# GitHub Action to greet people
# More info at https://github.com/portfolio-2025br/bootcamp-wex

---
name: Greetings

"on":
  pull_request_target:
    types: [opened]
  issues:
    types: [opened]

permissions:
  contents: read

jobs:
  greeting:
    runs-on: ubuntu-latest
    name: greetings

    permissions:
      issues: write
      pull-requests: write
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@4d991eb9b905ef189e4c376166672c3f2f230481 # v2.11.0
        with:
          disable-sudo: true
          egress-policy: block
          allowed-endpoints: >
            api.github.com:443

      - uses: actions/first-interaction@34f15e814fe48ac9312ccf29db4e74fa767cbab7 # v1.3.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: |
            Welcome and thank you for helping us improve our software.

            Please make sure you read and understand the CODE_OF_CONDUCT.md and CONTRIBUTING.md.
            We hope to see you soon!
          pr-message: |
            Wow, your first PR. Thank you.

            Please make sure you read and understand the CODE_OF_CONDUCT.md and CONTRIBUTING.md.
            We hope to see you soon!
